//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 09:12:45 AM CST 
//


package com.foundation.service.evaluate.xsdEntity.evaluationTemplate;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}exp" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rel" type="{}relType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "exp",
        "expGroup"
})
@XmlRootElement(name = "expGroup")
public class ExpGroup {

    protected List<Exp> exp;
    protected List<ExpGroup> expGroup;
    @XmlAttribute(name = "rel")
    protected RelType rel;

    /**
     * Gets the value of the exp property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exp property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExp().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Exp }
     *
     *
     */
    public List<Exp> getExp() {
        if (exp == null) {
            exp = new ArrayList<Exp>();
        }
        return this.exp;
    }

    /**
     * Gets the value of the expGroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expGroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpGroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpGroup }
     *
     *
     */
    public List<ExpGroup> getExpGroup() {
        if (expGroup == null) {
            expGroup = new ArrayList<ExpGroup>();
        }
        return this.expGroup;
    }

    /**
     * Gets the value of the rel property.
     *
     * @return
     *     possible object is
     *     {@link RelType }
     *
     */
    public RelType getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     *
     * @param value
     *     allowed object is
     *     {@link RelType }
     *
     */
    public void setRel(RelType value) {
        this.rel = value;
    }

}
